### ISSUE TITLE
README doesn't mention expected output

### ISSUE THREAD

**Issue by vinaybenny** [nz-social-investment-unit/social_investment_analytical_layer#1]
The readme needs to mention the expected output from running the main_sial.sas script and where to look for the outputs views and tables. The same needs to be done for uninstall_sial as well.

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve as many github issues as possible](https://trello.com/c/r9CSw7f6/61-resolve-as-many-github-issues-as-possible)

**Comment by vinaybenny** [comment]
The main_sial script and the readme mentions the outputs for each step in detail now. Resolved.
