### ISSUE TITLE
Uninstall does not remove MSD Tier 1 table

### ISSUE THREAD

**Issue by vinaybenny** [nz-social-investment-unit/social_investment_analytical_layer#2]
uninstall_sial_tables_views.sql does not remove MSD Tier 1 table.

**Comment by vinaybenny** [comment]
This has been fixed.

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve as many github issues as possible](https://trello.com/c/r9CSw7f6/61-resolve-as-many-github-issues-as-possible)
