### ISSUE TITLE
Add correct path in 'create_sial_views.sql'

### ISSUE THREAD

**Issue by conrad-mac** [nz-social-investment-unit/social_investment_analytical_layer#3]

**Comment by vinaybenny** [comment]
This has been rendered obsolete by the new mechanism by which the create_sial_views work. The paths are no longer required in the code.

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve as many github issues as possible](https://trello.com/c/r9CSw7f6/61-resolve-as-many-github-issues-as-possible)
