### ISSUE TITLE
Add IDI pre-requisites for use of SIAL

### ISSUE THREAD

**Issue by vinaybenny** [nz-social-investment-unit/social_investment_analytical_layer#5]
1. Directions for first time IDI users.
2. Pre-requisites for the use of SIAL.
3. Access levels required for using each SIAL table.

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Master dataset v1.0 guide](https://trello.com/c/zzhrm12r/5-master-dataset-v1-0-guide)

**Comment by vinaybenny** [comment]
Added descriptions to readme.
