### ISSUE TITLE
SIAL_selfharm_events.sql does not have schemaname qualifier

### ISSUE THREAD

**Issue by vinaybenny** [nz-social-investment-unit/social_investment_analytical_layer#6]
The view gets created in the user schema as a result. Need to fix.

**Comment by vinaybenny** [comment]
Fixed. Added the necessary reference

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve as many github issues as possible](https://trello.com/c/r9CSw7f6/61-resolve-as-many-github-issues-as-possible)
