### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by ellisp** [nz-social-investment-unit/social_investment_analytical_layer#7]
We should probably introduce [semantic versioning](http://semver.org/)

**Comment by ernestynne** [comment]
Currently specified in the readme.

In future we intend to tag releases so that it is clear when there are major prod releases and people an easily use an older version of SIAL if they wish

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve as many github issues as possible](https://trello.com/c/r9CSw7f6/61-resolve-as-many-github-issues-as-possible)
