### ISSUE TITLE
Corrections cost logic incorrect

### ISSUE THREAD

**Issue by ernestynne** [nz-social-investment-unit/social_investment_analytical_layer#9]
The code is not taking into account the fact that there are different daily corrections costs each year. The join will need to be adjusted to take into account the years.

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix corrections cost logic in IDI and github](https://trello.com/c/BBCl3VO7/71-fix-corrections-cost-logic-in-idi-and-github)

**Comment by vinaybenny** [comment]
Date joins have been added to the script such that start date of corrections event falls between the date ranges for each daily cost row in the costs dimension.
